CREATE DATABASE programacion CHARSET utf8mb4;

CREATE TABLE libro(
	id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    ICBN INT (13) NOT NULL,
    nombre VARCHAR(30) NOT NULL,
    autor VARCHAR(30) NOT NULL,
    genero VARCHAR(20) NOT NULL,
    fechaLanzamiento VARCHAR(15) NOT NULL,
    cantidadPaginas INT(10) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE socio(
	id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    nombre VARCHAR(30) NOT NULL,
    apellido VARCHAR(30) NOT NULL,
    telefono INT(20) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE prestamo(
	id INT UNSIGNED AUTO_INCREMENT NOT NULL,
	socio INT UNSIGNED NOT NULL,
    libro INT UNSIGNED NOT NULL,
    fechaPrestamo VARCHAR(15),
    fechaDevolucion VARCHAR(15),
	CONSTRAINT FK_socio FOREIGN KEY (socio) REFERENCES socio(id),
    CONSTRAINT FK_libro FOREIGN KEY (libro) REFERENCES libro(id),
    PRIMARY KEY(id)
);